// ─────────────────────────────────────────────────────────────────────────────
// JOB DATA - Extended with descriptions, responsibilities, and requirements
// ─────────────────────────────────────────────────────────────────────────────

export const jobDetails = [
  {
    id: "desarrollador-fullstack",
    title: "Desarrollador Full Stack",
    salaryRange: "USD 1,500 - 2,500",
    location: "Asuncion, PY",
    type: "Tiempo completo",
    area: "Ingenieria",
    href: "/carreras/desarrollador-fullstack",
    description: "Buscamos un Desarrollador Full Stack para unirse a nuestro equipo y ayudar a construir aplicaciones web modernas y escalables. Trabajaras en estrecha colaboracion con nuestros equipos de diseno y producto para crear interfaces de usuario intuitivas y sistemas backend robustos.",
    responsibilities: [
      "Desarrollar y mantener aplicaciones web full stack",
      "Colaborar con el equipo de diseno para implementar interfaces de usuario",
      "Disenar y optimizar bases de datos y APIs RESTful",
      "Participar en revisiones de codigo y mentorear a desarrolladores junior",
      "Implementar pruebas automatizadas y practicas de CI/CD",
    ],
    requirements: [
      "3+ anos de experiencia en desarrollo full stack",
      "Dominio de React, Next.js y TypeScript",
      "Experiencia con Node.js y bases de datos SQL/NoSQL",
      "Conocimiento de practicas de desarrollo agil",
      "Excelentes habilidades de comunicacion en espanol",
    ],
  },
  {
    id: "disenador-uxui",
    title: "Disenador UX/UI",
    salaryRange: "USD 1,200 - 2,000",
    location: "Remoto",
    type: "Tiempo completo",
    area: "Diseno",
    href: "/carreras/disenador-uxui",
    description: "Estamos buscando un Disenador UX/UI Senior para liderar el diseno de nuestros productos digitales. Seras responsable de crear experiencias de usuario excepcionales y mantener la coherencia visual en todas nuestras plataformas.",
    responsibilities: [
      "Liderar el diseno de nuevas funcionalidades y mejoras del sistema de diseno",
      "Colaborar con ingenieros para asegurar implementaciones de alta calidad",
      "Mentorear a disenadores junior y proporcionar feedback sobre su trabajo",
      "Crear y mantener documentacion de diseno",
      "Conducir investigacion de usuarios y pruebas de usabilidad",
    ],
    requirements: [
      "5+ anos de experiencia en diseno de productos",
      "Portfolio solido demostrando habilidades de UI/UX",
      "Experiencia con sistemas de diseno y bibliotecas de componentes",
      "Excelentes habilidades de comunicacion y colaboracion",
      "Familiaridad con herramientas de diseno modernas (Figma, Sketch)",
    ],
  },
  {
    id: "marketing-manager",
    title: "Marketing Manager",
    salaryRange: "USD 1,000 - 1,800",
    location: "Asuncion, PY",
    type: "Tiempo completo",
    area: "Marketing",
    href: "/carreras/marketing-manager",
    description: "Buscamos un Marketing Manager dinamico para liderar nuestras estrategias de marketing digital y posicionamiento de marca. Seras responsable de desarrollar campanas creativas que conecten con nuestra audiencia objetivo.",
    responsibilities: [
      "Desarrollar y ejecutar estrategias de marketing digital",
      "Gestionar campanas en redes sociales y publicidad digital",
      "Analizar metricas y optimizar el rendimiento de campanas",
      "Coordinar con el equipo de contenido para crear materiales de marketing",
      "Identificar oportunidades de crecimiento y nuevos canales",
    ],
    requirements: [
      "3+ anos de experiencia en marketing digital",
      "Conocimiento de herramientas de analytics y SEO",
      "Experiencia con plataformas de publicidad digital",
      "Habilidades creativas y analiticas",
      "Excelente comunicacion escrita y verbal",
    ],
  },
  {
    id: "dev-frontend",
    title: "Frontend Developer",
    salaryRange: "USD 1,200 - 2,000",
    location: "Remoto",
    type: "Tiempo completo",
    area: "Ingenieria",
    href: "/carreras/dev-frontend",
    description: "Unete a nuestro equipo como Frontend Developer y ayuda a crear interfaces de usuario modernas y responsivas. Trabajaras con las ultimas tecnologias web para construir experiencias excepcionales para nuestros usuarios.",
    responsibilities: [
      "Desarrollar componentes de UI reutilizables y accesibles",
      "Implementar disenos responsivos y optimizados para rendimiento",
      "Colaborar con disenadores UX/UI para traducir mockups en codigo",
      "Mantener y mejorar la base de codigo frontend existente",
      "Participar en decisiones de arquitectura frontend",
    ],
    requirements: [
      "2+ anos de experiencia en desarrollo frontend",
      "Dominio de React y TypeScript",
      "Experiencia con CSS moderno y preprocesadores",
      "Conocimiento de accesibilidad web (WCAG)",
      "Familiaridad con testing de componentes",
    ],
  },
  {
    id: "sales-representative",
    title: "Sales Representative",
    salaryRange: "USD 800 - 1,500",
    location: "Asuncion, PY",
    type: "Medio tiempo",
    area: "Ventas",
    href: "/carreras/sales-representative",
    description: "Buscamos un Sales Representative entusiasta para unirse a nuestro equipo comercial. Seras responsable de generar nuevas oportunidades de negocio y mantener relaciones con clientes existentes.",
    responsibilities: [
      "Prospectar y generar nuevas oportunidades de negocio",
      "Realizar presentaciones de productos y servicios",
      "Mantener relaciones con clientes existentes",
      "Cumplir con metas de ventas mensuales",
      "Reportar actividades y metricas de ventas",
    ],
    requirements: [
      "1+ ano de experiencia en ventas",
      "Excelentes habilidades de comunicacion",
      "Orientacion a resultados y metas",
      "Conocimiento del sector tecnologico (deseable)",
      "Disponibilidad para trabajar medio tiempo",
    ],
  },
  {
    id: "disenador-grafico",
    title: "Disenador Grafico",
    salaryRange: "USD 900 - 1,400",
    location: "Remoto",
    type: "Tiempo completo",
    area: "Diseno",
    href: "/carreras/disenador-grafico",
    description: "Estamos buscando un Disenador Grafico creativo para crear contenido visual impactante para nuestras marcas y clientes. Trabajaras en una variedad de proyectos desde branding hasta materiales de marketing digital.",
    responsibilities: [
      "Crear disenos graficos para redes sociales y marketing digital",
      "Desarrollar identidades visuales y materiales de branding",
      "Disenar presentaciones y documentos corporativos",
      "Colaborar con el equipo de marketing en campanas visuales",
      "Mantener la coherencia visual en todos los materiales",
    ],
    requirements: [
      "2+ anos de experiencia en diseno grafico",
      "Dominio de Adobe Creative Suite",
      "Portfolio demostrando versatilidad creativa",
      "Conocimiento de tendencias de diseno actuales",
      "Habilidad para trabajar en multiples proyectos simultaneamente",
    ],
  },
];

// Export areas for filtering
export const jobAreas = ["Todos", ...Array.from(new Set(jobDetails.map((job) => job.area)))];