import { IconType } from "react-icons";

import {
    HiChevronUp,
    HiChevronDown,
    HiChevronRight,
    HiChevronLeft,
    HiOutlineArrowPath,
    HiOutlineSun,
    HiOutlineMoon,
    HiOutlineQuestionMarkCircle,
    HiOutlineInformationCircle,
    HiOutlineExclamationTriangle,
    HiOutlineExclamationCircle,
    HiOutlineCheck,
    HiOutlineCheckCircle,
    HiOutlineDocumentDuplicate,
    HiOutlineEyeDropper,
    HiOutlineClipboard,
    HiOutlineUser,
    HiOutlineXMark,
    HiOutlineLink,
    HiArrowUpRight,
    HiOutlineMinus,
    HiOutlinePlus,
    HiOutlineCalendar,
    HiOutlineEye,
    HiOutlineEyeSlash,
    HiOutlineMagnifyingGlass,
    HiOutlineShieldCheck,
    HiOutlineSparkles,
    HiOutlineComputerDesktop,
    HiOutlineArrowsPointingIn,
    HiOutlineArrowsPointingOut,
    HiOutlineRocketLaunch,
    HiOutlineDocumentText,
    HiOutlineEnvelope,
    HiOutlineDocumentChartBar,
    HiOutlineSquares2X2,
    HiCog8Tooth,
    HiOutlineTicket,
    HiOutlineMapPin,
    HiOutlineClock,
    HiOutlineBriefcase,
    HiOutlineCurrencyDollar,
} from "react-icons/hi2";


export const iconLibrary: Record<string, IconType> = {
    chevronUp: HiChevronUp,
    chevronDown: HiChevronDown,
    chevronRight: HiChevronRight,
    chevronLeft: HiChevronLeft,
    refresh: HiOutlineArrowPath,
    light: HiOutlineSun,
    dark: HiOutlineMoon,
    help: HiOutlineQuestionMarkCircle,
    info: HiOutlineInformationCircle,
    warning: HiOutlineExclamationTriangle,
    danger: HiOutlineExclamationCircle,
    checkbox: HiOutlineCheck,
    check: HiOutlineCheckCircle,
    copy: HiOutlineDocumentDuplicate,
    eyeDropper: HiOutlineEyeDropper,
    clipboard: HiOutlineClipboard,
    person: HiOutlineUser,
    close: HiOutlineXMark,
    openLink: HiOutlineLink,
    arrowUpRight: HiArrowUpRight,
    minus: HiOutlineMinus,
    plus: HiOutlinePlus,
    calendar: HiOutlineCalendar,
    eye: HiOutlineEye,
    eyeOff: HiOutlineEyeSlash,
    search: HiOutlineMagnifyingGlass,
    security: HiOutlineShieldCheck,
    sparkle: HiOutlineSparkles,
    computer: HiOutlineComputerDesktop,
    minimize: HiOutlineArrowsPointingIn,
    maximize: HiOutlineArrowsPointingOut,
    rocket: HiOutlineRocketLaunch,
    pages: HiOutlineDocumentText,
    email: HiOutlineEnvelope,
    HiOutlineDocumentChartBar: HiOutlineDocumentChartBar,
    HiOutlineShieldCheck: HiOutlineShieldCheck,
    HiOutlineSquares2X2: HiOutlineSquares2X2,
    HiCog8Tooth: HiCog8Tooth,
    HiOutlineTicket: HiOutlineTicket,
    mapPin: HiOutlineMapPin,
    clock: HiOutlineClock,
    briefcase: HiOutlineBriefcase,
    currency: HiOutlineCurrencyDollar,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;